version: '3'
services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: kind_gould
    environment:
      - MONGO_INITDB_DATABASE=todoapp
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017